### PR TITLE
feat(cache): Updated cache action to v4

### PR DESCRIPTION
**Pull request by devlsat**

### CODE REVIEW

**Comment by kishaningithub** [comment]
Can you kindly rebase your PR with the main branch once? It should trigger a CI CD run.

**Comment by devlsat** [comment]
> Can you kindly rebase your PR with the main branch once? It should trigger a CI CD run.

I am not able to rebase, maybe due to lack of write access. Was just able to fork and create PR.
You can just update it in your next release if it's possible.

**Comment by kishaningithub** [comment]
If you point the `git remote` config to your fork you should be able to rebase

**Comment by devlsat** [comment]
Hi plz check now

**Comment by kishaningithub** [comment]
This node js change is breaking amazon linux 2 because it has an older version of GLIBC. What is the version of amazon linux are you using?

## Error screenshot
image

**Comment by devlsat** [comment]
I am on the Amazon Linux 2023. Yes, there are breaking changes, due to the older version of GLIBC 2.26 being used in Amazon Linux 2

**Comment by devlsat** [comment]
> You have any suggestions to fix this?

No idea, since it's on the Amazon side.

**Comment by kishaningithub** [comment]
One idea I am planning to explore

What if I remove the cache action and replace it with direct curl calls

That way I don't have to publish separate versions based on the Amazon Linux version

**Comment by devlsat** [comment]
> One idea I am planning to explore
> 
> What if I remove the cache action and replace it with direct curl calls
> 
> That way I don't have to publish separate versions based on the Amazon Linux version

Oh, that should work, would make it simpler as well to maintain in the longer run.

**Comment by devlsat** [comment]
Closing the pr

**Pull request closed without merging**
